export type ScienceQuestion = {
  id: string;
  number: string;
  category: string;
  title: string;
  prompt: string;
  options: string[];
  answer: string;
  hints: string[];
  explanation: string;
};

export const SCIENCE_QUESTIONS: ScienceQuestion[] = [
  { id: "bilim-01", number: "01", category: "Örüntü", title: "Işık dizisi", prompt: "Bir düzenekte ışıklar şu sırayla yanıyor: mavi, sarı, sarı, mavi, sarı, sarı... 11. ışık hangi renktir?", options: ["Mavi", "Sarı", "Kırmızı", "Yeşil", "Beyaz", "Mor", "Turuncu", "Renk yok"], answer: "Sarı", hints: ["Dizinin tekrar eden en kısa parçasını bul.", "Parçanın uzunluğunu 11 ile karşılaştır.", "11. konumun tekrar bloğundaki yerini işaretle."], explanation: "Düzen üçlü bloklar hâlinde tekrar eder; 11. konum üçüncü elemana denk gelir." },
  { id: "bilim-02", number: "02", category: "Sınıflandırma", title: "Enerji izleri", prompt: "Aşağıdakilerden hangisi diğerlerinden farklı bir enerji dönüşümünü temsil eder?", options: ["Güneş paneli", "Rüzgâr türbini", "Bisiklet dinamosu", "El feneri pili", "Su türbini", "Jeotermal santral", "Dalga jeneratörü", "Baraj"], answer: "El feneri pili", hints: ["Önce kaynak enerjisini ve çıkan enerjiyi iki sütuna ayır.", "Hareketten elektriğe dönüşenleri grupla.", "Bir seçenek kimyasal enerjiyi başlangıçta kullanıyor."], explanation: "El feneri pili kimyasal enerjiyi doğrudan elektrik enerjisine dönüştürür; diğerleri doğal hareket/ısı kaynaklarını kullanır." },
  { id: "bilim-03", number: "03", category: "Sıralama", title: "Gölge saati", prompt: "Güneş yükselirken bir çubuğun gölgesi kısalıyor. Gölge uzunluğunun en büyük olduğu zaman hangisidir?", options: ["Gün doğumuna yakın", "Öğle vakti", "Gün batımına yakın", "Tam tepede", "Her zaman aynı", "Gece yarısı", "Bulutlu anda", "Rüzgârlı anda"], answer: "Gün doğumuna yakın", hints: ["Güneş ışınlarının geliş açısını düşün.", "Çubuk ile ışın arasındaki açı küçüldükçe gölgeyi karşılaştır.", "Güneş ufka en yakınken gölgeyi gözünde canlandır."], explanation: "Güneş ufka yakınken ışınlar daha yatay gelir ve çubuk daha uzun gölge oluşturur." },
  { id: "bilim-04", number: "04", category: "Ölçme", title: "Eşit hacim", prompt: "Aynı miktarda su üç kaba konuyor. Su seviyesi en çok hangi kapta yükselir?", options: ["En dar kapta", "En geniş kapta", "En uzun kapta", "Her kapta eşit", "Yuvarlak kapta", "Metal kapta", "Şeffaf kapta", "Kap şekline bağlı değil"], answer: "En dar kapta", hints: ["Hacim aynı, taban alanları farklı.", "Aynı miktar su daha az alana yayılırsa yükseklik ne olur?", "Su seviyesini değil, tabandaki alanı karşılaştır."], explanation: "Aynı hacim daha dar tabana yayıldığında yükseklik daha büyük olur." },
  { id: "bilim-05", number: "05", category: "Mantık", title: "Araştırma kuralı", prompt: "Bir deneyde yalnızca bitki ışık alırsa büyüyor. Işık almayan ama su alan bitki için hangi sonuç kesin söylenebilir?", options: ["Bu deneyde büyüme gözlenmedi", "Kesinlikle öldü", "Kesinlikle büyüdü", "Su etkisizdir", "Işık her şeyi açıklar", "Toprak gereksizdir", "Bitki deney yapılamaz", "Sonuç rastlantıdır"], answer: "Bu deneyde büyüme gözlenmedi", hints: ["Sorudaki kesin bilgiyi aşma.", "Gözlenmeyen sonucu, bitkinin tüm geleceğiyle karıştırma.", "Yalnız bu deney koşulunda ne görüldüğüne odaklan."], explanation: "Verilen gözlem yalnız bu koşulda büyüme olmadığını destekler; daha geniş iddialar için ek deney gerekir." },
  { id: "bilim-06", number: "06", category: "Grafik", title: "Sıcaklık izi", prompt: "Bir termometre 8, 11, 14, 17 değerlerini gösteriyor. Aynı artış sürerse bir sonraki değer nedir?", options: ["18", "19", "20", "21", "22", "23", "24", "25"], answer: "20", hints: ["Ardışık iki ölçüm arasındaki farkları yaz.", "Farklar aynı mı kontrol et.", "Son ölçüme aynı adımı ekle."], explanation: "Her ölçüm 3 artıyor; 17 + 3 = 20." },
  { id: "bilim-07", number: "07", category: "Harita", title: "Kısa rota", prompt: "Bir robot kuzeye 3, doğuya 4 kare gidiyor. Başlangıçtan uzaklığını kuş uçuşu düşünürsek kaç karedir?", options: ["3", "4", "5", "6", "7", "8", "12", "14"], answer: "5", hints: ["Kuzey ve doğu hareketleri dik iki kenar oluşturur.", "3-4-5 üçgenini hatırla.", "Toplam yolu değil, doğrudan uzaklığı soruyor."], explanation: "Dik üçgende uzaklık √(3²+4²) = 5 karedir." },
  { id: "bilim-08", number: "08", category: "Olasılık", title: "Renkli taşlar", prompt: "Bir torbada 3 kırmızı ve 1 mavi taş var. Bakmadan çekilen taşın kırmızı olma olasılığı hangi kesirdir?", options: ["1/4", "1/3", "1/2", "2/3", "3/4", "3/5", "4/3", "1"], answer: "3/4", hints: ["Önce toplam taş sayısını bul.", "Kırmızı taşların sayısını toplam sayıya böl.", "Kesir sadeleşiyor mu kontrol et."], explanation: "Toplam 4 taşın 3’ü kırmızı olduğu için olasılık 3/4’tür." },
  { id: "bilim-09", number: "09", category: "Deney tasarımı", title: "Adil karşılaştırma", prompt: "Bir öğrenci farklı kâğıt uçakların uçuş mesafesini karşılaştırıyor. Adil deney için hangisini sabit tutmalıdır?", options: ["Atış kuvvetini", "Uçağın rengini", "Kâğıdın desenini", "İsimlerini", "Masadaki saati", "Gözlemcinin yerini", "Fotoğrafı", "Sıralama rengini"], answer: "Atış kuvvetini", hints: ["Değiştirmek istediği şey uçak modeli.", "Sonucu etkileyebilecek başka bir değişken seç.", "Her uçağa aynı başlangıç koşulunu vermek gerekir."], explanation: "Modelleri karşılaştırırken atış kuvveti gibi sonucu etkileyen koşullar aynı tutulmalıdır." },
  { id: "bilim-10", number: "10", category: "Algoritma", title: "Mikroskop sırası", prompt: "Bir gözlem algoritması önce örneği yerleştiriyor, sonra ışığı açıyor, sonra netliyor. Netlikten önce hangi adım gelmelidir?", options: ["Işığı açmak", "Örneği yerleştirmek", "Sonucu yazmak", "Mikroskobu kaldırmak", "Örneği boyamak", "Defteri kapatmak", "Fotoğrafı silmek", "Hiçbiri"], answer: "Işığı açmak", hints: ["Algoritmadaki sıralı adımları aynen yaz.", "Netlik ayarından hemen önceki adımı bul.", "İlk adımdan sonraki işlem soruluyor."], explanation: "Verilen sırada yerleştirmeden sonra ışık açılır, ardından netlik ayarlanır." },
  { id: "bilim-11", number: "11", category: "Strateji", title: "En az tartım", prompt: "9 özdeş kutudan biri diğerlerinden ağır. Eşit kollu terazide ağır kutuyu bulmak için en iyi ilk hamle hangisidir?", options: ["Hepsini tek tek tartmak", "3’e 3 tartmak", "1’e 1 tartmak", "9’unu aynı kefeye koymak", "Kutuları sallamak", "Renklerine bakmak", "Hiç tartmamak", "İkişer tartmak"], answer: "3’e 3 tartmak", hints: ["Her tartımda olasılıkları olabildiğince eşit böl.", "9 nesneyi üç gruba ayır.", "İki kefeye aynı sayıda kutu koy."], explanation: "3’e 3 tartım, ağır kutunun hangi üçlüde olduğunu tek hamlede belirler; denge varsa üçüncü grup kalır." },
  { id: "bilim-12", number: "12", category: "Kodlama", title: "Sensör kararı", prompt: "Sensör değeri 7. Kural: değer 5’ten büyükse yeşil, değilse kırmızı ışık yanıyor. Hangi ışık yanar?", options: ["Yeşil", "Kırmızı", "Mavi", "Sarı", "İkisi", "Hiçbiri", "Beyaz", "Mor"], answer: "Yeşil", hints: ["7 ile 5’i karşılaştır.", "Büyük olma koşulunun hangi dala gittiğini bul.", "Koşul doğruysa ilk seçeneği kullan."], explanation: "7, 5’ten büyük olduğu için yeşil ışık yanar." },
  { id: "bilim-13", number: "13", category: "Veri", title: "Sıralı kayıt", prompt: "Bir gözlem listesi 2, 5, 5, 8, 10 değerlerinden oluşuyor. Ortadaki değer hangisidir?", options: ["2", "5", "6", "7", "8", "10", "30", "0"], answer: "5", hints: ["Liste zaten küçükten büyüğe sıralı.", "Eleman sayısını say.", "Ortadaki konumu iki yana eşit uzaklıkta bul."], explanation: "Beş değerli sıralı listenin üçüncü, yani ortanca değeri 5’tir." },
  { id: "bilim-14", number: "14", category: "Optimizasyon", title: "Güneş paneli", prompt: "Küçük bir güneş paneli gün boyunca en çok ışığı toplamak için hangi konumda olmalıdır?", options: ["Işığa dönük", "Tamamen kapalı", "Gölgenin altında", "Duvara dönük", "Yere gömülü", "Rastgele", "Su içinde", "Gece yönünde"], answer: "Işığa dönük", hints: ["Panelin görevi ışığı enerjiye çevirmek.", "Işıkla karşılaşan yüzey alanını düşün.", "Gölge ve kapalı yüzeyleri ele."], explanation: "Panelin ışık kaynağına dönük olması üzerine düşen ışığı artırır." },
  { id: "bilim-15", number: "15", category: "Çıkarım", title: "Ses dalgası", prompt: "Bir davulun derisine daha sert vurulduğunda sesin hangi özelliği artar?", options: ["Şiddeti", "Yayılma yönü", "Dalga boyu kesinlikle", "Hızı kesinlikle", "Rengi", "Kütlesi", "Sıcaklığı", "Kokusu"], answer: "Şiddeti", hints: ["Daha sert vurmak titreşim enerjisini değiştirir.", "Sesin yüksek/alçak algısıyla sesin güçlü/zayıf algısını ayır.", "Soruda sesin fiziksel gücü soruluyor."], explanation: "Daha büyük titreşim genliği sesin şiddetini artırır; bu, sesin daha güçlü duyulmasıdır." },
  { id: "bilim-16", number: "16", category: "Hata ayıklama", title: "Kırık ölçüm", prompt: "Bir deneyde üç ölçüm 12, 13, 40 çıkıyor. İlk iki ölçüm birbirine yakınken üçüncüyü kontrol etmek için en mantıklı adım nedir?", options: ["Üçüncü ölçümü tekrarlamak", "İlk ikisini silmek", "Sonucu yuvarlamak", "40’ı gizlemek", "Deneyi bırakmak", "Hepsini 40 yapmak", "Cihazı boyamak", "Rastgele sayı seçmek"], answer: "Üçüncü ölçümü tekrarlamak", hints: ["Şüpheli değer için kanıtı artır.", "Ölçümü ve cihazı yeniden kontrol et.", "Veriyi değiştirmek yerine gözlemi yinele."], explanation: "Diğer ölçümlerden ayrılan değeri doğrulamanın en güvenilir yolu ölçümü aynı koşullarda tekrarlamaktır." },
  { id: "bilim-17", number: "17", category: "Döngü", title: "Filtre adımları", prompt: "Bir su filtresi her turda 2 parçacık azaltıyor. Başlangıçta 10 parçacık varsa üç tur sonunda kaç parçacık kalır?", options: ["2", "4", "6", "8", "10", "12", "14", "16"], answer: "4", hints: ["Her turdaki değişimi yaz.", "Üç kez 2 azaltmayı hesapla.", "Azalma miktarını başlangıçtan çıkar."], explanation: "10 − 2 − 2 − 2 = 4 parçacık kalır." },
  { id: "bilim-18", number: "18", category: "Kombinasyon", title: "Araştırma ekibi", prompt: "3 farklı gözlem aracı ve 2 farklı kayıt defteri arasından birer tane seçilecek. Kaç farklı ikili oluşturulabilir?", options: ["2", "3", "4", "5", "6", "8", "9", "12"], answer: "6", hints: ["Her araç, her defterle eşleşebilir.", "Bir aracın kaç eşleşmesi olduğunu bul.", "Araç sayısı ile defter sayısını çarp."], explanation: "3 araç × 2 defter = 6 farklı ikili." },
  { id: "bilim-19", number: "19", category: "Strateji", title: "Köprü ışıkları", prompt: "Bir keşif ekibi karanlık köprüden geçecek. Bir fener var ve en fazla iki kişi birlikte geçebiliyor. Güvenli geçişte ilk ilke hangisidir?", options: ["Fener her geçişte bulunmalı", "Feneri geride bırakmak", "Herkesi tek başına göndermek", "Süreyi ölçmemek", "Köprüyü koşarak geçmek", "Feneri kapatmak", "Rastgele eşleşmek", "Köprüyü görmezden gelmek"], answer: "Fener her geçişte bulunmalı", hints: ["Karanlıkta güvenliği sağlayan tek aracı takip et.", "Her geçişin başlangıç ve bitiş koşulunu düşün.", "Fener olmadan yapılan geçiş kurala uymaz."], explanation: "Köprü karanlık olduğu için her geçişte fenerin geçen kişilerle birlikte olması gerekir." },
  { id: "bilim-20", number: "20", category: "Çok adımlı akıl yürütme", title: "Ekosistem dengesi", prompt: "Bir gölette algler artınca su bulanıyor, ışık azalıyor ve su bitkileri küçülüyor. Bu zincirde doğrudan gözlenen ilk neden hangisidir?", options: ["Alglerin artması", "Bitkilerin küçülmesi", "Işığın azalması", "Suyun kaynaması", "Balıkların yok olması", "Gölün büyümesi", "Yağmurun durması", "Sıcaklığın sıfırlanması"], answer: "Alglerin artması", hints: ["Zinciri başlangıçtan sona doğru oku.", "Diğer olayları başlatan gözlemi bul.", "İlk neden ile sonraki sonuçları karıştırma."], explanation: "Verilen zincir alglerin artmasıyla başlıyor; bulanıklık ve ışık azalması sonraki sonuçlar." },
];
