import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BILFEN_CAMPUSES } from "@shared/campuses";
import { BarChart3, Building2, Users } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";

export default function CampusReport() {
  const { user, loading } = useAuth();
  const [, setLocation] = useLocation();
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const periodInput = useMemo(() => {
    if (!fromDate && !toDate) return undefined;
    const from = fromDate ? new Date(`${fromDate}T00:00:00`) : undefined;
    const to = toDate ? new Date(`${toDate}T23:59:59`) : undefined;
    return { from, to };
  }, [fromDate, toDate]);
  const previousPeriodInput = useMemo(() => {
    if (!periodInput?.from || !periodInput.to) return undefined;
    const length = periodInput.to.getTime() - periodInput.from.getTime();
    return { from: new Date(periodInput.from.getTime() - length - 86400000), to: new Date(periodInput.from.getTime() - 86400000) };
  }, [periodInput]);
  const report = trpc.admin.campusReport.useQuery(periodInput, { enabled: user?.role === "admin" });
  const previousReport = trpc.admin.campusReport.useQuery(previousPeriodInput, { enabled: user?.role === "admin" && Boolean(previousPeriodInput) });
  useEffect(() => { if (!loading && !user) setLocation("/giris"); }, [loading, setLocation, user]);

  if (loading) return <main className="min-h-screen grid place-items-center bg-[#f6f2e8] text-[#173d59]">Rapor hazırlanıyor…</main>;
  if (!user) return null;
  if (user.role !== "admin") return <main className="min-h-screen grid place-items-center bg-[#f6f2e8] p-6 text-center text-[#173d59]"><div><h1 className="text-3xl font-bold">Yönetici erişimi gerekli</h1><p className="mt-3 text-[#6b6456]">Kampüs karşılaştırma raporu yalnızca kampüs yöneticileri içindir.</p><Link href="/ogretmen" className="mt-6 inline-block font-semibold underline">Öğretmen merkezine dön</Link></div></main>;

  const rows = report.data ?? [];
  const previousRows = previousReport.data ?? [];
  const maxAtlas = Math.max(1, ...rows.map(row => row.atlasCompletion), ...previousRows.map(row => row.atlasCompletion));
  const maxScience = Math.max(1, ...rows.map(row => row.averageScienceScore));

  return <main className="min-h-screen bg-[#f6f2e8] px-4 py-8 text-[#173d59] sm:px-8"><div className="mx-auto max-w-7xl space-y-8"><header className="rounded-3xl bg-[#0d4d64] p-7 text-white shadow-lg sm:p-9"><p className="font-mono text-xs tracking-[0.16em] text-[#f1d36b]">BİLFEN KAMPÜS YÖNETİMİ</p><h1 className="mt-2 text-3xl font-bold">Kampüs karşılaştırma raporu</h1><p className="mt-2 max-w-3xl text-white/80">Aktif öğrencilerin Atlas rota tamamlanması ve Bilim ve Zekâ başarısı kampüs bazında karşılaştırılır. Veriler yalnızca kayıtlı gerçek öğrenci sonuçlarından hesaplanır.</p></header><section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-bold">Dönem filtresi</h2><p className="mt-1 text-sm text-[#746e61]">Tarih seçildiğinde önceki eş uzunluktaki dönemle gelişim karşılaştırılır.</p></div><div className="flex flex-wrap items-end gap-3"><label className="text-sm font-semibold">Başlangıç<input type="date" value={fromDate} onChange={event => setFromDate(event.target.value)} className="mt-1 block rounded-xl border border-[#cbded2] p-2" /></label><label className="text-sm font-semibold">Bitiş<input type="date" value={toDate} onChange={event => setToDate(event.target.value)} className="mt-1 block rounded-xl border border-[#cbded2] p-2" /></label><button type="button" onClick={() => { setFromDate(""); setToDate(""); }} className="rounded-xl border border-[#cbded2] px-3 py-2 text-xs font-bold">Tüm dönem</button></div></div></section>
    {report.isLoading ? <p className="rounded-2xl bg-white p-6">Kampüs verileri okunuyor…</p> : report.isError ? <p role="alert" className="rounded-2xl bg-[#fff1eb] p-6 text-[#8b382e]">Rapor verisi yüklenemedi. Yetki veya bağlantı durumunu kontrol edin.</p> : rows.length === 0 ? <p className="rounded-2xl bg-white p-6">Henüz karşılaştırılabilir aktif öğrenci verisi bulunmuyor.</p> : <>
      {periodInput && previousPeriodInput && <section className="rounded-3xl bg-[#edf5ef] p-6 shadow-sm"><h2 className="text-xl font-bold">Dönemler arası gelişim</h2><p className="mt-1 text-sm text-[#5d766f]">Seçili dönem ile hemen önceki eş uzunluktaki dönemin Atlas ve Bilim/Zekâ puan farkı.</p><div className="mt-6 space-y-5">{rows.map(row => { const previousRow = previousRows.find(item => item.campusKey === row.campusKey); const previous = previousRow?.atlasCompletion ?? 0; const previousScience = previousRow?.averageScienceScore ?? 0; const delta = row.atlasCompletion - previous; const scienceDelta = row.averageScienceScore - previousScience; return <div key={`delta-${row.campusKey}`}><div className="flex items-center justify-between gap-3 text-sm"><strong>{BILFEN_CAMPUSES.find(campus => campus.key === row.campusKey)?.name ?? row.campusKey}</strong><span className={delta >= 0 ? "font-bold text-[#1e604d]" : "font-bold text-[#bd594b]"}>{delta >= 0 ? "+" : ""}{delta} puan</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-[#dce8df]"><i className="block h-full rounded-full bg-[#43887d]" style={{ width: `${Math.min(100, Math.max(0, row.atlasCompletion))}%` }} /></div><small className="mt-1 block text-[#746e61]">Atlas · Önceki: %{previous} · Seçili: %{row.atlasCompletion}</small><div className="mt-3 flex items-center justify-between gap-3 text-xs"><strong className="text-[#bd594b]">Bilim ve Zekâ puanı</strong><span className={scienceDelta >= 0 ? "font-bold text-[#1e604d]" : "font-bold text-[#bd594b]"}>{scienceDelta >= 0 ? "+" : ""}{scienceDelta} puan</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-[#f0dfd9]"><i className="block h-full rounded-full bg-[#bd594b]" style={{ width: `${Math.min(100, Math.max(0, row.averageScienceScore * 5))}%` }} /></div><small className="mt-1 block text-[#746e61]">Bilim/Zekâ · Önceki: {previousScience} · Seçili: {row.averageScienceScore}</small></div>; })}</div></section>}
      <section className="grid gap-4 sm:grid-cols-3" aria-label="Kampüs raporu özeti"><article className="rounded-2xl bg-white p-5 shadow-sm"><Building2 className="text-[#397d75]" size={20} /><strong className="mt-3 block text-3xl">{rows.length}</strong><span className="text-sm text-[#746e61]">Verisi bulunan kampüs</span></article><article className="rounded-2xl bg-white p-5 shadow-sm"><Users className="text-[#397d75]" size={20} /><strong className="mt-3 block text-3xl">{rows.reduce((sum, row) => sum + row.students, 0)}</strong><span className="text-sm text-[#746e61]">Aktif öğrenci</span></article><article className="rounded-2xl bg-white p-5 shadow-sm"><BarChart3 className="text-[#bd594b]" size={20} /><strong className="mt-3 block text-3xl">%{Math.round(rows.reduce((sum, row) => sum + row.atlasCompletion, 0) / rows.length)}</strong><span className="text-sm text-[#746e61]">Ortalama Atlas tamamlanması</span></article></section>
      <section className="grid gap-7 lg:grid-cols-2"><article className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Atlas rota tamamlanması</h2><p className="mt-1 text-sm text-[#746e61]">35 görev üzerinden kampüs ortalamaları.</p><div className="mt-6 space-y-5">{rows.map(row => <div key={`atlas-${row.campusKey}`}><div className="flex items-center justify-between gap-3 text-sm"><strong>{BILFEN_CAMPUSES.find(campus => campus.key === row.campusKey)?.name ?? row.campusKey}</strong><span>%{row.atlasCompletion}</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-[#e8eee8]" role="img" aria-label={`${row.campusKey} Atlas tamamlanması yüzde ${row.atlasCompletion}`}><i className="block h-full rounded-full bg-[#43887d]" style={{ width: `${Math.round(row.atlasCompletion / maxAtlas * 100)}%` }} /></div><small className="mt-1 block text-[#746e61]">{row.students} aktif öğrenci</small></div>)}</div></article><article className="rounded-3xl bg-[#fffaf1] p-6 shadow-sm"><h2 className="text-xl font-bold">Bilim ve Zekâ puanları</h2><p className="mt-1 text-sm text-[#746e61]">20 soru üzerinden benzersiz doğru cevap puanı.</p><div className="mt-6 space-y-5">{rows.map(row => <div key={`science-${row.campusKey}`}><div className="flex items-center justify-between gap-3 text-sm"><strong>{BILFEN_CAMPUSES.find(campus => campus.key === row.campusKey)?.name ?? row.campusKey}</strong><span>{row.averageScienceScore} puan · %{row.scienceSuccessRate}</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-[#f0dfd9]" role="img" aria-label={`${row.campusKey} Bilim ve Zekâ puanı ${row.averageScienceScore}, başarı yüzde ${row.scienceSuccessRate}`}><i className="block h-full rounded-full bg-[#bd594b]" style={{ width: `${Math.round(row.averageScienceScore / maxScience * 100)}%` }} /></div><small className="mt-1 block text-[#746e61]">20 soru başarı oranı: %{row.scienceSuccessRate}</small></div>)}</div></article></section>
      <section className="overflow-x-auto rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Kampüs veri tablosu</h2><table className="mt-4 w-full min-w-[720px] text-left text-sm"><caption className="sr-only">Kampüs karşılaştırma verileri</caption><thead className="border-b text-xs uppercase tracking-wide text-[#746e61]"><tr><th className="pb-3">Kampüs</th><th className="pb-3">Öğrenci</th><th className="pb-3">Atlas</th><th className="pb-3">Bilim puanı</th><th className="pb-3">Bilim başarı</th></tr></thead><tbody>{rows.map(row => <tr key={row.campusKey} className="border-b border-[#eee9df]"><td className="py-3 font-semibold">{BILFEN_CAMPUSES.find(campus => campus.key === row.campusKey)?.name ?? row.campusKey}</td><td className="py-3">{row.students}</td><td className="py-3">%{row.atlasCompletion}</td><td className="py-3">{row.averageScienceScore}</td><td className="py-3">%{row.scienceSuccessRate}</td></tr>)}</tbody></table></section>
    </>}
  </div></main>;
}
